apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: gotest
  name: gotest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gotest
  template:
    metadata:
      labels:
        name: gotest
    spec:
      containers:
      - image: toszo/myunit-epiphany-example-code #it will pull latest
        imagePullPolicy: Always
        name: gotest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always