apiVersion: v1
kind: Service
metadata:
  labels:
    name: gotest
  name: gotest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: gotest
  sessionAffinity: None
  type: ClusterIP
